[project]
name = "helix-cli"

[local.dev]
port = 6969
build_mode = "debug"

[cloud.helix-cli.FlyIo]
cluster_id = "974af638-d9f6-4492-8d81-81763a524664"
build_mode = "debug"
vm_size = "shared-cpu-1x"
volume = "helix-helix-cli-helix-cli-data:/data"
volume_initial_size = 20
privacy = "Public"
auth_type = "Cli"
