use crate::commands::ai::{SetupOptions, setup};
use std::fs;
use tempfile::TempDir;

fn test_dir() -> TempDir {
    TempDir::new().expect("failed to create temp dir")
}

#[test]
fn test_ai_setup_creates_default_files() {
    let dir = test_dir();

    let result = setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: None,
        yes: true,
        force: false,
        copy_prompt: false,
    });

    assert!(result.is_ok(), "ai setup should succeed: {result:?}");

    assert!(dir.path().join("HELIX_AI_SETUP_PROMPT.md").exists());
    assert!(dir.path().join("AGENTS.md").exists());
    assert!(
        dir.path()
            .join(".claude/skills/helix-author-hql/SKILL.md")
            .exists()
    );
    assert!(
        dir.path()
            .join(".claude/skills/helix-mcp-tools/SKILL.md")
            .exists()
    );
    assert!(
        dir.path()
            .join(".claude/skills/helix-cli-workflows/SKILL.md")
            .exists()
    );

    // Optional targets should not be generated by default
    assert!(!dir.path().join(".cursor/rules/helix.mdc").exists());
    assert!(!dir.path().join(".github/copilot-instructions.md").exists());
    assert!(!dir.path().join("CODEX_SETUP.md").exists());
}

#[test]
fn test_ai_setup_is_idempotent() {
    let dir = test_dir();

    setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: Some("claude".to_string()),
        yes: true,
        force: false,
        copy_prompt: false,
    })
    .expect("first setup should succeed");

    let prompt_path = dir.path().join("HELIX_AI_SETUP_PROMPT.md");
    let first = fs::read_to_string(&prompt_path).expect("read prompt after first setup");

    setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: Some("claude".to_string()),
        yes: true,
        force: false,
        copy_prompt: false,
    })
    .expect("second setup should succeed");

    let second = fs::read_to_string(&prompt_path).expect("read prompt after second setup");
    assert_eq!(first, second, "setup should be idempotent");
}

#[test]
fn test_ai_setup_skips_existing_changes_without_force() {
    let dir = test_dir();

    setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: None,
        yes: true,
        force: false,
        copy_prompt: false,
    })
    .expect("setup should succeed");

    let agents_path = dir.path().join("AGENTS.md");
    fs::write(&agents_path, "custom agents instructions\n").expect("write custom AGENTS");

    setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: None,
        yes: true,
        force: false,
        copy_prompt: false,
    })
    .expect("setup should succeed when files differ");

    let content = fs::read_to_string(&agents_path).expect("read AGENTS after setup");
    assert_eq!(content, "custom agents instructions\n");
}

#[test]
fn test_ai_setup_force_overwrites_existing_changes() {
    let dir = test_dir();

    setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: None,
        yes: true,
        force: false,
        copy_prompt: false,
    })
    .expect("setup should succeed");

    let agents_path = dir.path().join("AGENTS.md");
    fs::write(&agents_path, "custom agents instructions\n").expect("write custom AGENTS");

    setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: None,
        yes: true,
        force: true,
        copy_prompt: false,
    })
    .expect("forced setup should succeed");

    let content = fs::read_to_string(&agents_path).expect("read AGENTS after force");
    assert!(
        content.contains("Generated by `helix ai setup`"),
        "force should overwrite with generated content"
    );
}

#[test]
fn test_ai_setup_copy_prompt_non_fatal() {
    let dir = test_dir();

    let result = setup(SetupOptions {
        path: Some(dir.path().to_string_lossy().to_string()),
        agents: None,
        yes: true,
        force: false,
        copy_prompt: true,
    });

    assert!(
        result.is_ok(),
        "copy prompt failures should not fail setup: {result:?}"
    );
}
