//! Supported language/operator families exercised by the plan matrix.
pub(super) const CYPHER: &[(&str, &str)] = &[
    ("scan", "MATCH (n:User) RETURN n"),
    ("unlabeled_scan", "MATCH (n) RETURN n LIMIT 10"),
    ("equality", "MATCH (n:User {key:7}) RETURN n.key"),
    ("unique", "MATCH (n:User {email:'a'}) RETURN n.email"),
    ("membership", "MATCH (n:User) WHERE n.key IN [1,2,3] RETURN n.key"),
    ("intersection", "MATCH (n:User) WHERE n.key=7 AND n.region='eu' RETURN n"),
    ("disjunction", "MATCH (n:User) WHERE n.key=7 OR n.key=8 RETURN n"),
    ("range", "MATCH (n:User) WHERE n.age>=21 AND n.age<65 RETURN n.age"),
    ("range_ascending", "MATCH (n:User) WHERE n.age>=21 RETURN n.age ORDER BY n.age LIMIT 10"),
    ("range_descending", "MATCH (n:User) WHERE n.age>=21 RETURN n.age ORDER BY n.age DESC LIMIT 10"),
    ("zero_limit", "MATCH (n:User) RETURN n.key LIMIT 0"),
    ("skip_limit", "MATCH (n:User) RETURN n.key SKIP 100 LIMIT 10"),
    ("composed_limits", "MATCH (n:User) WITH n SKIP 5 LIMIT 100 RETURN n.key SKIP 2 LIMIT 3"),
    ("filter_limit", "MATCH (n:User) WHERE n.age%2=0 RETURN n.key LIMIT 10"),
    ("late_error", "MATCH (n:User) RETURN 1/n.age AS v LIMIT 1"),
    ("chain", "MATCH (a:User)-[:FOLLOWS]->(b:User)-[:FOLLOWS]->(c:User) RETURN c.key LIMIT 10"),
    ("selective_tail", "MATCH (a:User)-[:FOLLOWS]->(b:User)-[:FOLLOWS]->(c:User {email:'a'}) RETURN a.key"),
    ("reverse", "MATCH (a:User)<-[:FOLLOWS]-(b:User) RETURN b.key LIMIT 10"),
    ("undirected", "MATCH (a:User)-[:FOLLOWS]-(b:User) RETURN b.key LIMIT 10"),
    ("star", "MATCH (a:User)-[:FOLLOWS]->(b:User),(a)-[:FOLLOWS]->(c:User),(a)-[:FOLLOWS]->(d:User) RETURN b.key,c.key,d.key"),
    ("cycle", "MATCH (a:User)-[:FOLLOWS]->(b:User)-[:FOLLOWS]->(c:User)-[:FOLLOWS]->(a) RETURN a.key"),
    ("bound_endpoint", "MATCH (a:User {key:1}),(b:User {key:2}) MATCH (a)-[:FOLLOWS]->(b) RETURN a,b"),
    ("path", "MATCH p=(a:User)-[:FOLLOWS]->(b:User) RETURN nodes(p),relationships(p) LIMIT 10"),
    ("relationship_properties", "MATCH (a:User)-[r:FOLLOWS {weight:1}]->(b:User) RETURN r.weight LIMIT 10"),
    ("product", "MATCH (a:User),(b:User) RETURN a.key,b.key LIMIT 10"),
    ("equality_join", "MATCH (a:User),(b:User) WHERE a.key=b.key RETURN a.key,b.key"),
    ("multi_join", "MATCH (a:User),(b:User),(c:User) WHERE a.key=b.key AND b.region=c.region RETURN a.key,c.key"),
    ("correlated_lookup", "UNWIND [1,2,3] AS key MATCH (n:User {key:key}) RETURN n.key"),
    ("optional", "MATCH (a:User) OPTIONAL MATCH (a)-[:FOLLOWS]->(b:User) RETURN a.key,b.key"),
    ("optional_predicate", "MATCH (a:User) OPTIONAL MATCH (a)-[:FOLLOWS]->(b:User) WHERE b.age>21 RETURN a.key,b.key"),
    ("optional_then_filter", "MATCH (a:User) OPTIONAL MATCH (a)-[:FOLLOWS]->(b:User) WITH a,b WHERE b.age>21 RETURN a.key,b.key"),
    ("optional_lookup", "UNWIND [1,2,3] AS key OPTIONAL MATCH (n:User {key:key}) RETURN key,n.key"),
    ("unwind", "MATCH (n:User) UNWIND [n.key,n.age] AS v RETURN v LIMIT 10"),
    ("distinct", "MATCH (n:User) RETURN DISTINCT n.region"),
    ("distinct_limit", "MATCH (n:User) RETURN DISTINCT n.region LIMIT 3"),
    ("count", "MATCH (n:User) RETURN count(*)"),
    ("group", "MATCH (n:User) RETURN n.region,count(*),avg(n.age) ORDER BY n.region"),
    ("group_distinct", "MATCH (n:User) RETURN n.region,count(DISTINCT n.key)"),
    ("collect", "MATCH (n:User) RETURN n.region,collect(n.key)"),
    ("top_k", "MATCH (n:User) RETURN n.key,n.age ORDER BY n.age DESC SKIP 5 LIMIT 10"),
    ("ordered_hidden", "MATCH (n:User) RETURN n.key ORDER BY n.age LIMIT 10"),
    ("scope_shadow", "MATCH (n:User) WITH n.key AS n RETURN n LIMIT 10"),
    ("create", "UNWIND [1,2,3] AS key CREATE (:User {key:key})"),
    ("read_write", "MATCH (n:User) SET n.age=n.age+1 RETURN n.key"),
    ("remove", "MATCH (n:User {key:7}) REMOVE n.age RETURN n"),
    ("delete", "MATCH (n:User {key:7}) DELETE n"),
    ("detach_delete", "MATCH (n:User {key:7}) DETACH DELETE n"),
    ("write_read", "CREATE (n:User {key:7}) WITH n MATCH (m:User {key:7}) RETURN m.key"),
    ("shared_disjunction", "MATCH (n:User) WHERE n.region='eu' AND (n.key=7 OR n.key=8) RETURN n.key"),
    ("unique_disjunction", "MATCH (n:User) WHERE n.email='a' OR n.email='b' RETURN n.email"),
];
