//! SDK requests under both absent and available search-index catalogs.
use super::{matrix, Input, Query};
use helix_planner::{catalog, context};
use std::collections::BTreeMap;

/// Full generated SDK corpus is opt-in because it is generated by SDK parity.
/// Missing or changed fixture denominators fail instead of shrinking coverage.
pub fn sdk_inputs(root: &std::path::Path, expected: usize) -> BTreeMap<String, Input> {
    fn visit(root: &std::path::Path, files: &mut Vec<std::path::PathBuf>) {
        for entry in std::fs::read_dir(root).expect("SDK fixture directory") {
            let path = entry.unwrap().path();
            if path.is_dir() {
                visit(&path, files);
            } else if path
                .extension()
                .is_some_and(|extension| extension == "json")
            {
                files.push(path);
            }
        }
    }
    let mut files = Vec::new();
    visit(root, &mut files);
    files.sort();
    assert_eq!(files.len(), expected, "full SDK fixture denominator");
    let mut inputs = BTreeMap::new();
    for file in files {
        let request: helix_ast::query::QueryRequest =
            serde_json::from_slice(&std::fs::read(&file).unwrap()).unwrap();
        for profile in matrix::PROFILES {
            let mut context = context::PlannerContext::default();
            for (name, value) in request.parameters().into_iter().flatten() {
                let name = helix_planner::ir::NonEmptyString::new(name.clone()).unwrap();
                context.params = context
                    .params
                    .with_value(name.clone(), helix_ast::value::PropertyValue::from(value))
                    .with_query_value(name, value.clone());
            }
            matrix::profile(&mut context, profile);
            for active_search in [false, true] {
                let mut context = context.clone();
                if active_search {
                    // Match the four search-index definitions in SDK fixture 024.
                    for (element, label, text) in [
                        (catalog::ElementKind::Node, "ParityUser", "bio"),
                        (catalog::ElementKind::Edge, "FOLLOWS", "note"),
                    ] {
                        context.indexes = context
                            .indexes
                            .with_vector(
                                catalog::SearchIndexKey::try_new(element, label, "embedding")
                                    .unwrap(),
                                catalog::SearchIndexScope::Unscoped,
                            )
                            .with_text(
                                catalog::SearchIndexKey::try_new(element, label, text).unwrap(),
                                catalog::SearchIndexScope::Unscoped,
                            );
                    }
                }
                let key = format!(
                    "sdk/{}/storage={profile}/search={active_search}",
                    file.strip_prefix(root).unwrap().display()
                );
                assert!(inputs
                    .insert(
                        key,
                        Input {
                            query: Query::Native(Box::new(request.query().clone())),
                            context,
                        }
                    )
                    .is_none());
            }
        }
    }
    inputs
}
