// Placeholder - will be generated by build.rs
pub struct HandlerMetadata {
    pub name: &'static str,
    pub param_struct: Option<&'static str>,
    pub return_type: Option<&'static str>,
}

pub const HANDLERS: &[HandlerMetadata] = &[];
